### ISSUE TITLE
Data Consisteny issues 

### ISSUE THREAD

**Issue by neerajgupta2407** [mayple/swydo#1]
I have observed that the data fetched via python library is different than actual response returned by Swydo.

Reason: Dupllicate records in reponse.
PFB snippet

```
from swydo import SwydoClient
SWYDO_DEFAULT_TEAM_ID =  ''
SWYDO_API_AUTH_TOKEN=''
swydo_client = SwydoClient(SWYDO_API_AUTH_TOKEN)
reports = swydo_client.getTeamReports(SWYDO_DEFAULT_TEAM_ID)
reps = [r for r in reports]
print(len(reps))  # 3909
# Count unique Reports.
len(set([a['id'] for a in reps])) # 3362
```

**Comment by advance512** [comment]
@neerajgupta2407 As I cannot reproduce this issue, can you debug it and offer a fix? 
A PR would be more than welcome.

**Comment by neerajgupta2407** [comment]
@advance512 This issue is coming due to inconsistencies in SWYDO API's
When you iterate request in method getTeamReports, sometimes swydo returns same results in multiple requests leading to duplicate and inconsistent data.
Alternative solution to get the team reports with iterating over clients.

```
    def getAllClientReports(self, team_id):
        response = []
        clients = self.getTeamClients(team_id)
        for client in clients:
            client_reports = self.getReportsByClient(team_id, client['id'])
            response.extend(client_reports)
        return response


```
